version: "3.8"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./artifacts:/app/artifacts
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
